{% set name = "trajan" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ef4259ceda979ce6fd374651259253fb6b63b80c3bda966446bfb34df694a0c5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - trajanshow = trajan.scripts.trajanshow:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry >=1
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy >=1.23
    - scipy >=1.9
    - xarray >=2022.6.0
    - pandas >=2
    - matplotlib-base >=3.5
    - cartopy >=0.21
    - pyproj >=2.3
    - click >=8
    - cf_xarray >=0.8
    - netcdf4 >=1.6
    - bottleneck >=1.3
    - roaring-landmask >=0.7

test:
  imports:
    - trajan
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - trajanshow --help

about:
  home: https://github.com/OpenDrift/trajan
  summary: Trajectory analysis package for simulated and observed trajectories
  description: Trajectory analysis package for simulated and observed trajectories
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  doc_url: https://opendrift.github.io/trajan/
  dev_url: https://github.com/OpenDrift/trajan

extra:
  recipe-maintainers:
    - gauteh
    - knutfrode
